server:
  port: 9999
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:database
    data-username: sa
    data-password:
    data: classpath:db/data.sql
    #schema: classpath:db/schema.sql
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: DEBUG
trace: true
